language: node_js
node_js:
- 10.9.0

before_install:
- openssl aes-256-cbc -K $encrypted_d4f7565e6ead_key -iv $encrypted_d4f7565e6ead_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud -q app deploy

cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"

install:
- npm install
