language: node_js
node_js:
- 10.9.0
before_install:
- openssl aes-256-cbc -K $encrypted_d4f7565e6ead_key -iv $encrypted_d4f7565e6ead_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- openssl aes-256-cbc -K $encrypted_4cb330591e04_key -iv $encrypted_4cb330591e04_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz
- npm i -g npm@version-number
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
